### ISSUE TITLE
Add support for engine hooks

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#40]
Add a system to execute sh commands on the following events:

* pre-startup
* post-startup
* pre-shutdown
* post-shutdown

Let the user specify optional strings inside the config file for these hooks to be executed inside `sh -c '…'`.

**Comment by main--** [comment]
On second thought, perhaps it would be more appropriate to let the environment handle these things? If you're running `windows-gaming-driver` in systemd (as you should), you can just configure all these hooks right there (even post-startup because the unit only transitions from `starting` to `running` when the GA connects). If not, it's even easier - just use a wrapper script.

**Comment by oberien** [comment]
Given I manually start windows-gaming, I can see your point to just use a wrapper script.
But given I run windows-gaming in systemd user mode, I don't really want to write systemd services to execute stuff on startup / shutdown. It's pretty complicated and not something most users would think about / would do.

**Comment by main--** [comment]
You don't need to create special units - just create an override file for ExecStartPre/ExecStartPost/ExecStop/ExecStopPost, whatever you need.

This is really not any more complex than adding the commands to our config file (it's basically just a matter of where to write them). Perhaps we should document this trick but I don't see any reason to reimplement a mechanism that already exists.

**Comment by oberien** [comment]
If using systemd: `systemctl [--user] edit windows.service`, then write:
```ini
[Service]
ExecStartPre=/bin/sh -c 'foo bar'
```
